repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
    exclude: "docs/site_libs/"
  - id: end-of-file-fixer
    exclude: "docs/site_libs/"
  - id: trailing-whitespace
    exclude: "docs/site_libs/"
    exclude_types: [svg]
  - id: check-added-large-files
    args: ['--maxkb=95000']
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.1.3
  hooks:
  - id: style-files
    args: [--style_pkg=styler, --style_fun=tidyverse_style]
