---
title: "Collecting song and artist data"
description: |
  Annotating the data downloaded from Spotify with more specific and descriptive data using Spotify's API.
author:
  - first_name: "Joshua"
    last_name: "Cook"
    url: https://joshuacook.netlify.app
    orcid_id: 0000-0001-9815-6879
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "#>", eval = FALSE)

library(memoise)
library(tidyverse)

# To shut-up `summarise()`.
options(dplyr.summarise.inform = FALSE)

cache_path <- here::here(".memoise")

walk(list.files("lib", pattern = "R$", full.names = TRUE), source)
```

> **This notebook is still a work-in-progress.**
> Currently, none of the code is run, so the notebook will appear blank.

```{r}
get_playlist_memo <- memoise(
  spotifyr::get_playlist,
  cache = cache_filesystem(cache_path)
)

get_my_playlists_memo <- memoise(
  spotifyr::get_my_playlists,
  cache = cache_filesystem(cache_path)
)

get_track_memo <- memoise(
  spotifyr::get_track,
  cache = cache_filesystem(cache_path)
)

get_track_audio_features_memo <- memoise(
  spotifyr::get_track_audio_features,
  cache = cache_filesystem(cache_path)
)

get_track_audio_analysis_memo <- memoise(
  spotifyr::get_track_audio_analysis,
  cache = cache_filesystem(cache_path)
)
```

Get all of my playlists.

```{r, echo=TRUE}
my_playlists <- get_my_playlists_memo(limit = 50) %>%
  as_tibble() %>%
  janitor::clean_names() %>%
  select(name, id, uri, tracks_total)
```

```{r}
display_head(my_playlists)
```

For each playlist, get all of the information.

```{r, echo=TRUE}
get_playlist_info <- function(playlist_id) {
  get_playlist_memo(playlist_id = playlist_id)$tracks$items %>%
    as_tibble() %>%
    janitor::clean_names() %>%
    select(
      track_name, track_id, track_uri, track_artists, track_duration_ms,
      track_popularity, track_album_name, track_album_id, track_album_uri,
      track_album_release_date, track_album_release_date_precision,
      track_explicit
    )
}

playlist_df <- my_playlists %>%
  mutate(data = map(id, get_playlist_info))
```

For each track, get the "features" and "analysis" from Spotify.

```{r}
clean_track_info <- function(x) {
  tibble(
    album_id = x$album$id,
    album_name = x$album$name,
    duration = x$duration_ms,
    explicit = x$explicit,
    track_id = x$id,
    track_uri = x$uri,
    track_name = x$name,
    popularity = x$popularity,
    album_info = list(x$album),
    release_date = x$album$release_date,
    release_date_precision = x$album$release_date_precision
  )
}

clean_track_features <- function(x) {
  janitor::clean_names(x)
}

clean_track_analysis <- function(x) {
  x[-c(1:2)] %>%
    map(list) %>%
    as_tibble()
}


get_track_data <- function(id) {
  bind_cols(
    get_track_memo(id = id) %>% clean_track_info(),
    get_track_audio_features_memo(id = id) %>% clean_track_features(),
    get_track_audio_analysis_memo(id = id) %>% clean_track_analysis()
  )
}

get_track_data <- memoise(get_track_data, cache = cache_filesystem(cache_path))
```


```{r}
stacy_id <- "07ZQLYn9x4x3L3vxStc1zr"
stacy_track_data <- get_track_data(stacy_id)
```
