---
title: "Analyzing my track details"
description: |
  A deep analysis of some of my favorite songs.
author:
  - first_name: "Joshua"
    last_name: "Cook"
    url: https://joshuacook.netlify.app
    orcid_id: 0000-0001-9815-6879
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "#>")

library(nakedpipe)
library(mustashe)
library(magrittr)
library(ggthemes)
library(ggrepel)
library(ggtext)
library(patchwork)
library(tidyverse)

# To shut-up `summarise()`.
options(dplyr.summarise.inform = FALSE)

theme_set(ggthemes::theme_fivethirtyeight())
pal_538 <- deframe(ggthemes_data[["fivethirtyeight"]])

walk(list.files("lib", pattern = "R$", full.names = TRUE), source)

track_info_df <- readRDS(here::here("data", "track_detailed_info.rds"))
playlist_df <- readRDS(here::here("data", "playlist_detailed_info.rds"))

set.seed(0)

point_overrise_aes <- list(size = 1.5, alpha = 1)
```

```{r}
track_to_playlist_map <- playlist_df %.% {
  select(playlist_name = name, playlist_id = id, data)
  unnest(data)
  select(playlist_name:track_id)
  distinct()
  group_by(track_name, track_id)
  nest()
  rename(playlist_data = data)
}

background_playlists <- c(
  "Coffee Shop Sounds", "Deep Focus", "Good Bakcground",
  "Your Favorite Coffeehouse", "Emotional Sounds", "Peaceful Nature"
)

instrumental_playlists <- c("Instrumental", "Classical Playlist")

ignore_playlists <- c("Discover Weekly")

regular_playlists <- unique(playlist_df$name)
idx <- regular_playlists %in% c(
  background_playlists,
  instrumental_playlists,
  ignore_playlists
)
regular_playlists <- regular_playlists[!idx]
```


1. Explore the data from a single track.
2. Cluster/compare all tracks by their info.
  - HiPlot
  - heatmap of similarities
  - PCA & t-SNE

## Analysis of track segments of *Good Things Fall Apart* by Illenium featuring Jon Bellion

```{r}
single_track_info <- track_info_df %>%
  filter(track_name == "Good Things Fall Apart (with Jon Bellion)")
```

```{r}
single_track_sections <- as_tibble(single_track_info$sections[[1]])
rmarkdown::paged_table(single_track_sections)
```

```{r}
bind_rows(
  single_track_info$bars[[1]] %>% add_column(type = "bars"),
  single_track_info$beats[[1]] %>% add_column(type = "beats"),
  single_track_info$tatums[[1]] %>% add_column(type = "tatums")
) %.%
  {
    as_tibble()
  } %>%
  ggplot(aes(x = start, y = duration, color = type)) +
  facet_wrap(~type, scales = "free_y", ncol = 1) +
  geom_point(alpha = 0.5) +
  scale_color_fivethirtyeight() +
  theme(
    plot.title = element_markdown(),
    legend.position = "none"
  ) +
  labs(
    x = "time (ms)",
    y = "confidence",
    title = "Duration of timing features"
  )
```

```{r}
bind_rows(
  single_track_info$bars[[1]] %>% add_column(type = "bars"),
  single_track_info$beats[[1]] %>% add_column(type = "beats"),
  single_track_info$tatums[[1]] %>% add_column(type = "tatums")
) %.%
  {
    as_tibble()
  } %>%
  ggplot(aes(x = start, y = confidence, color = type)) +
  facet_wrap(~type, ncol = 1) +
  geom_hline(
    yintercept = 0.5,
    color = pal_538["Dark Gray"],
    size = 1,
    alpha = 0.7
  ) +
  geom_point(alpha = 0.5) +
  geom_smooth(
    method = "loess",
    formula = "y~x",
    span = 0.2,
    se = FALSE
  ) +
  scale_color_fivethirtyeight() +
  theme(
    legend.position = "none",
    axis.title.x = element_text(),
    axis.title.y = element_text()
  ) +
  labs(
    x = "time (ms)",
    y = "confidence",
    title = "Confidence in declaration of song timing features"
  )
```

```{r}
stacy_segment_tidy <- single_track_info$segments[[1]] %.% {
  as_tibble()
  mutate(
    idx = row_number(),
    loudness_max = map(loudness_max, ~ c(.))
  )
  select(idx, start, loudness_max, pitches, timbre)
  pivot_longer(-c(idx, start))
  unnest(value)
}

stacy_segment_tidy %>%
  ggplot(aes(x = start, y = value, color = name)) +
  facet_wrap(~name, scales = "free_y", ncol = 1) +
  geom_point(size = 0.5, alpha = 0.3) +
  scale_color_fivethirtyeight(guide = FALSE) +
  theme(
    plot.title = element_markdown(),
    axis.title.x = element_text()
  ) +
  labs(
    title = "Segment analysis of *Stacy*",
    x = "time point"
  )
```

```{r}
stacy_segment_tidy %.%
  {
    filter(name == "pitches")
    group_by(idx, start)
    summarise(avg_pitch = mean(value))
    ungroup()
  } %>%
  ggplot(aes(x = start, y = avg_pitch)) +
  geom_point(
    size = 1,
    alpha = 0.9,
    color = pal_538["Blue"]
  ) +
  geom_smooth(
    method = "loess",
    formula = "y~x",
    span = 0.5,
    color = colorspace::darken(pal_538["Blue"], 0.3)
  ) +
  theme(
    plot.title = element_markdown(),
    axis.title.x = element_text()
  ) +
  labs(
    title = "Average pitch",
    x = "time"
  )
```

```{r}
tibble(pitches = unlist(single_track_info$segments[[1]]$pitches)) %>%
  ggplot(aes(x = pitches)) +
  geom_histogram(breaks = seq(0, 1, 0.05)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = expansion(c(0, 0.02))) +
  labs(title = "Distribution of pitch")
```

---

## Comparing tracks by their quantifiable musical features

```{r}
add_playlist_names <- function(df,
                               playlist_df,
                               by = c("track_name", "track_id")) {
  left_join(df, playlist_df, by = by) %>%
    mutate(playlist = map_chr(playlist_data, function(df) {
      if (nrow(df) > 1) {
        return("multiple")
      }
      return(df$playlist_name[[1]])
    }))
}

add_playlist_groups <- function(df) {
  df %>%
    mutate(playlist_grp = case_when(
      playlist_name %in% background_playlists ~ "Background",
      playlist_name %in% instrumental_playlists ~ "Instrumental",
      playlist_name %in% regular_playlists ~ "Rock & Hip Hop",
      playlist_name %in% ignore_playlists ~ "Discover Weekly"
    ))
}

group_playlist_groups <- function(df, ...) {
  df %>%
    select(...) %>%
    group_by(...) %>%
    distinct() %>%
    summarise(
      playlist_grp = ifelse(n() > 1, "multiple", playlist_grp)
    ) %>%
    ungroup()
}
```

```{r}
track_info_df %.%
  {
    select(track_id, danceability:tempo)
    mutate_if(is.numeric, scale_numeric)
    distinct()
    left_join(track_to_playlist_map, by = "track_id")
    unnest(playlist_data)
    add_playlist_groups()
    select(-c(track_name, playlist_id, playlist_name))
    pivot_longer(
      -c(track_id, playlist_grp),
      names_to = "feature",
      values_to = "value"
    )
  } %>%
  ggplot(aes(x = feature, y = value, group = track_id)) +
  facet_wrap(~playlist_grp, ncol = 2, scales = "free_y") +
  geom_line(aes(color = playlist_grp), alpha = 0.1) +
  theme(
    axis.text.x = element_text(angle = 30, hjust = 1),
    legend.position = "none"
  )
```

```{r}
track_metrics <- track_info_df %>%
  select(track_id, danceability:tempo) %>%
  mutate_if(is.numeric, scale_numeric) %>%
  distinct() %>%
  group_by(track_id) %>%
  nest() %>%
  deframe()


stash("track_similarities", depends_on = "track_metrics", {
  track_similarities <- expand_grid(
    from = names(track_metrics),
    to = names(track_metrics)
  ) %.% {
    filter(from != to)
    mutate(
      cos_similarity = map2_dbl(from, to, function(a, b) {
        x <- unlist(track_metrics[a])
        y <- unlist(track_metrics[b])
        cosine_similarity(x, y)
      })
    )
  }
})
```

```{r}
track_similarities %>%
  ggplot(aes(x = cos_similarity)) +
  geom_histogram(
    aes(y = ..density..),
    binwidth = 0.1,
    fill = spotify_dark,
    alpha = 0.5
  ) +
  geom_density(
    size = 1.5,
    color = spotify_dark
  ) +
  scale_x_continuous(
    expand = c(0, 0),
    breaks = seq(-1, 1, 0.25)
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.02))
  ) +
  theme(
    axis.title.x = element_text()
  ) +
  labs(
    x = "cosine similarity",
    y = "density",
    title = "Distribution of song similarities"
  )
```

```{r, fig.height=6}
track_sim_mat <- track_similarities %.% {
  pivot_wider(id = from, names_from = to, values_from = cos_similarity)
  as.data.frame()
  column_to_rownames("from")
  as.matrix()
}

# track_sim_mat <- track_sim_mat[1:200, 1:200]
clusters <- hclust(dist(track_sim_mat))
track_order <- clusters$labels[clusters$order]

track_label_plot <- track_to_playlist_map %.%
  {
    ungroup()
    unnest(playlist_data)
    distinct(track_id, playlist_name)
    add_playlist_groups()
    filter(track_id %in% track_order)
    mutate(track_id = factor(track_id, track_order))
  } %>%
  ggplot(aes(x = track_id, y = 1, fill = playlist_grp)) +
  geom_tile() +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  scale_fill_brewer(
    type = "qual", palette = "Set1",
    guide = guide_legend(
      title = "playlist",
      ncol = 1,
      direction = "vertical"
    )
  ) +
  theme(
    axis.text = element_blank(),
    legend.position = "right",
    legend.key.size = unit(4, "mm"),
    plot.margin = margin()
  )

track_sim_matrix_plot <- track_similarities %.%
  {
    filter(from %in% track_order & to %in% track_order)
    mutate(
      from = factor(from, levels = track_order),
      to = factor(to, levels = track_order)
    )
  } %>%
  ggplot(aes(x = from, y = to, fill = cos_similarity)) +
  geom_tile(color = NA) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  scale_fill_gradient2(
    guide = guide_colorbar(
      title = "similarity",
      barwidth = unit(4, "mm"),
      direction = "vertical"
    )
  ) +
  theme(
    panel.grid.major = element_blank(),
    axis.text = element_blank(),
    legend.position = "right",
    plot.margin = margin(),
    plot.title = element_text(size = 14)
  ) +
  labs(
    title = "Clustering of tracks by similarity of music metrics"
  )

(
  (track_sim_matrix_plot / track_label_plot) + plot_layout(heights = c(20, 1)) |
    guide_area()
) + plot_layout(widths = c(5, 1), guides = "collect")
```


```{r}
track_features <- track_info_df %.% {
  select(track_name:album_name, danceability:tempo)
}

track_features_mat <- track_features %.% {
  select(track_id, danceability:tempo)
  as.data.frame()
  column_to_rownames("track_id")
}

track_pca <- prcomp(
  track_features_mat,
  scale. = TRUE,
  center = TRUE
)

track_pcs_df <- track_features %.% {
  select(track_name:album_name)
  bind_cols(track_pca$x[, 1:2] %>% as_tibble())
  add_playlist_names(track_to_playlist_map)
}
```

```{r}
as.data.frame(t(summary(track_pca)$importance)) %.%
  {
    janitor::clean_names()
    rownames_to_column("PC")
    mutate(PC = as.numeric(str_remove(PC, "^PC")))
  } %>%
  ggplot(aes(PC, proportion_of_variance)) +
  geom_col(fill = "grey50", width = 0.7) +
  geom_line(color = colorspace::darken(spotify_green), size = 1, lty = 2) +
  geom_point(color = colorspace::darken(spotify_green), size = 3) +
  scale_x_continuous(
    breaks = 1:20
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.02)),
    breaks = seq(0, 0.4, 0.05),
  ) +
  theme(
    axis.title.x = element_text(),
    axis.title.y = element_text(),
    panel.grid.major.x = element_blank()
  ) +
  labs(
    x = "principal components",
    y = "porportion of variance"
  )
```

```{r}
track_pca$rotation %.%
  {
    as.data.frame()
    rownames_to_column(var = "feature")
    as_tibble()
  } %>%
  ggplot(aes(PC1, PC2)) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  ggrepel::geom_label_repel(
    aes(label = feature),
    fill = spotify_dark,
    color = "white",
    label.size = 0,
    fontface = "bold",
    label.padding = unit(1.3, "mm"),
    label.r = unit(1, "mm")
  ) +
  theme(
    axis.title.x = element_text(),
    axis.title.y = element_text()
  ) +
  labs(
    x = "PC1",
    y = "PC2",
    title = "Contribution of song features to decomposition"
  )
```

```{r, fig.height=8}
plot_track_pca <- function(df, x, y, color = NULL, size = NULL, alpha = 0.6) {
  df %>%
    ggplot(aes(x = {{ x }}, y = {{ y }})) +
    geom_point(aes(color = {{ color }}, size = {{ size }}), alpha = alpha) +
    theme(
      axis.title.x = element_text(),
      axis.title.y = element_text(),
      legend.title = element_blank()
    )
}

plot_track_pca(track_pcs_df, PC1, PC2, color = playlist) +
  scale_color_discrete(
    guide = guide_legend(nrow = 6, override.aes = point_overrise_aes)
  )
```

```{r, fig.height=7}
track_pcs_df %.%
  {
    unnest(playlist_data)
    add_playlist_groups()
    group_playlist_groups(track_name, track_id, PC1, PC2, playlist_grp)
  } %>%
  plot_track_pca(PC1, PC2, color = playlist_grp) +
  scale_color_brewer(
    type = "qual", palette = "Set1",
    guide = guide_legend(nrow = 1, override.aes = point_overrise_aes)
  ) +
  labs(
    x = "PC1",
    y = "PC2",
    title = "PCA: Playlist Category"
  )
```

```{r, fig.height=7}
track_pcs_df %.%
  {
    left_join(
      track_features %>% select(-c(album_name, album_id)),
      by = c("track_name", "track_id")
    )
    mutate(
      acousticness = scale_numeric(acousticness),
      loudness = scale_numeric(loudness),
      color = loudness - acousticness,
    )
  } %>%
  plot_track_pca(
    PC1,
    PC2,
    color = color,
    alpha = 1
  ) +
  annotate(
    "text",
    x = c(-1.2, 1.2), y = -3,
    label = c("Acousticness", "Loudness"),
    color = c("#3775B9", "#FE5B31"),
    size = 5,
    fontface = "bold",
    hjust = c(1, 0)
  ) +
  annotate(
    "segment",
    x = 0, y = -3, xend = c(-0.7, 0.7), yend = -3,
    arrow = arrow(length = unit(2, "mm"), type = "closed")
  ) +
  scale_color_distiller(type = "div", palette = "RdYlBu") +
  scale_size_continuous(range = c(1, 3)) +
  labs(
    x = "PC1",
    y = "PC2",
    title = "Distribution of the features defining PC1"
  )
```

```{r, fig.height=7}
track_tsne_data <- as.data.frame(track_features_mat) %.% {
  rownames_to_column("track_id")
  mutate_if(is.numeric, scale_numeric)
  column_to_rownames("track_id")
  distinct()
}

track_tsne <- track_tsne_data %>%
  Rtsne::Rtsne()

track_tsne_df <- as_tibble(track_tsne$Y) %.% {
  mutate(track_id = rownames(track_tsne_data))
  add_playlist_names(track_to_playlist_map, by = "track_id")
}

track_tsne_df %>%
  plot_track_pca(V1, V2, color = playlist) +
  scale_color_discrete(
    guide = guide_legend(nrow = 6, override.aes = point_overrise_aes)
  ) +
  labs(
    x = "t-SNE 1",
    y = "t-SNE 2",
    title = "t-SNE: Separation by playlist"
  )
```


```{r, fig.height=7}
track_tsne_df %.%
  {
    unnest(playlist_data)
    add_playlist_groups()
    group_playlist_groups(track_name, track_id, V1, V2, playlist_grp)
  } %>%
  plot_track_pca(V1, V2, color = playlist_grp) +
  scale_color_brewer(
    type = "qual", palette = "Set1",
    guide = guide_legend(nrow = 1, override.aes = point_overrise_aes)
  ) +
  labs(
    x = "t-SNE 1",
    y = "t-SNE 2",
    title = "t-SNE: Separation by playlist category"
  )
```
