---
title: "Analyzing my streaming history"
description: |
  Identifying trends in my listening habits.
author:
  - first_name: "Joshua"
    last_name: "Cook"
    url: https://joshuacook.netlify.app
    orcid_id: 0000-0001-9815-6879
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "#>", dpi = 500)

library(nakedpipe)
library(magrittr)
library(ggthemes)
library(ggrepel)
library(tidyverse)

theme_set(ggthemes::theme_fivethirtyeight())
pal_538 <- deframe(ggthemes_data[["fivethirtyeight"]])

walk(list.files("lib", pattern = "R$", full.names = TRUE), source)

streaming_history <- readRDS(here::here("data", "streaming_history.rds"))

min_song_length <- 60 * 1
```

Minimum length of a song `r round(min_song_length, 1)` seconds.

```{r}
notable_lengths <- tibble(
  song = c("Stacy", "Good Things Fall Apart", "Choices"),
  length = c("2:49", "3:37", "6:28"),
  x = c(169, 217, 388),
  y = c(0.010, 0.010, 0.0112)
) %.% {
  mutate(length = as.numeric(lubridate::ms(length)))
}

# TODO: cover the [0 -> min_song_len] with an area (replacing the dashed line)

streaming_history %>%
  ggplot(aes(x = sec_played)) +
  geom_density(fill = pal_538["Medium Gray"], alpha = 0.7) +
  geom_rect(
    data = tibble(sec_played = 0),
    xmin = 0, xmax = min_song_length,
    ymin = 0, ymax = Inf,
    fill = "grey20",
    alpha = 0.2,
    color = NA
  ) +
  geom_vline(
    xintercept = min_song_length,
    color = "grey35",
    lty = 2,
    alpha = 0.8
  ) +
  geom_vline(
    aes(xintercept = length, color = song),
    data = notable_lengths,
    size = 1,
    alpha = 0.8
  ) +
  geom_label(
    aes(label = song, x = x, y = y, color = song),
    data = notable_lengths,
    hjust = c(1, 0, 0),
    nudge_x = c(-10, 10, 10),
    alpha = 0.7,
    label.size = 0,
    family = "sans",
    fontface = "bold"
  ) +
  scale_x_continuous(
    expand = expansion(mult = c(0, 0.02)),
    limits = c(0, 600),
    breaks = seq(0, 10, 2) * 60,
    labels = function(x) {
      round(x / 60, 1)
    }
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0)),
    limits = c(0, 0.012)
  ) +
  scale_color_fivethirtyeight() +
  theme(
    axis.title = element_text(),
    legend.position = "none"
  ) +
  labs(
    x = "time spent listening to a song (min)",
    y = "density",
    title = "The distribution of play time",
    subtitle = paste(
      "Most songs were listened to for about 2-5 minutes. Some example song",
      "durations are labeled. The far-left peak (highlighted in grey) represents",
      "songs that were quickly skipped.",
      sep = "\n"
    )
  )
```

```{r}
streaming_history %.%
  {
    mutate(
      cum_sec_played = cumsum(sec_played),
      cum_hour_played = cum_sec_played / 60 / 60
    )
  } %>%
  ggplot(aes(x = end_time, y = cum_hour_played)) +
  geom_ribbon(
    aes(ymin = 0, ymax = cum_hour_played),
    alpha = 0.2,
    fill = spotify_dark
  ) +
  geom_line(size = 1, color = spotify_green) +
  scale_x_datetime(
    date_breaks = "2 months",
    date_labels = "%b %Y",
    expand = expansion(add = c(0, 0))
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.02))) +
  theme(
    axis.title.y = element_text()
  ) +
  labs(
    y = "time (hours)",
    title = "Cumulative time spent listening to Spotify"
  )
```


```{r}
streaming_history %<>% filter(sec_played >= min_song_length)
```


```{r}
streaming_history %.%
  {
    mutate(date = lubridate::floor_date(end_time, "day"))
    count(date)
  } %>%
  ggplot(aes(x = date, y = n)) +
  geom_point(alpha = 0.8) +
  geom_smooth(
    method = "loess",
    formula = "y~x",
    color = spotify_green
  ) +
  scale_x_datetime(
    date_breaks = "2 months",
    date_labels = "%b %Y",
    expand = expansion(add = c(0, 0))
  ) +
  theme(
    axis.title.y = element_text()
  ) +
  labs(
    y = "number of songs",
    title = "Daily number of songs listened to"
  )
```


```{r}
plot_barcount <- function(df, x, y,
                          x_lbl, title,
                          nudge_text = 11, expand_x = 0.08, wrap_y = Inf) {
  df %.%
    {
      mutate(label = scales::comma({{ x }}, accuracy = 1))
    } %>%
    ggplot(aes(x = {{ x }}, y = {{ y }})) +
    geom_col(fill = spotify_dark2, color = NA) +
    geom_text(
      aes(label = label),
      hjust = 0,
      family = "Helvetica",
      size = 3.5,
      nudge_x = nudge_text
    ) +
    scale_x_continuous(expand = expansion(c(0, expand_x))) +
    scale_y_discrete(labels = scales::label_wrap(wrap_y)) +
    theme_fivethirtyeight() +
    theme(
      panel.grid.major.y = element_blank(),
      axis.title.x = element_text()
    ) +
    labs(
      x = x_lbl,
      y = NULL,
      title = title
    )
}

streaming_history %.%
  {
    count(artist_name, sort = TRUE, name = "n")
    head(10)
    mutate(artist_name = fct_rev(fct_inorder(artist_name)))
  } %>%
  plot_barcount(
    x = n,
    y = artist_name,
    x_lbl = "number of times listened",
    title = "Top-10 most listened to artists",
    expand_x = 0.11,
    wrap_y = 30
  )
```

```{r}
streaming_history %.%
  {
    count(track_name, artist_name, sort = TRUE, name = "n")
    head(10)
    mutate(track_name = fct_rev(fct_inorder(track_name)))
  } %>%
  plot_barcount(
    x = n,
    y = track_name,
    x_lbl = "number of times listened",
    title = "Top-10 most listened to songs",
    nudge_text = 2,
    expand_x = 0.06,
    wrap_y = 30
  )
```

```{r, fig.height=6}
ignore_top_artists <- c(
  "Background Noise From TraxLab", "Ambient Sounds from I'm In Records"
)

top_artists <- streaming_history %.% {
  filter(!artist_name %in% !!ignore_top_artists)
  count(artist_name, sort = TRUE)
  head(6)
  pull(artist_name)
  unlist()
  unique()
}

streaming_history %.%
  {
    filter(artist_name %in% !!top_artists)
    group_by(artist_name)
    count(track_name, sort = TRUE)
    slice(1:5)
    ungroup()
    mutate(track_name = fct_rev(fct_inorder(track_name)))
  } %>%
  plot_barcount(
    x = n,
    y = track_name,
    x_lbl = "number of times listened",
    title = "Top songs of my favorite artists",
    nudge_text = 3,
    expand_x = 0.20,
    wrap_y = 30
  ) +
  facet_wrap(~artist_name, ncol = 2, scales = "free") +
  theme(strip.text = element_text(face = "bold"))
```

```{r}
top_songs <- streaming_history %.% {
  count(artist_name, track_name, sort = TRUE)
  head(6)
  select(track_name, artist_name)
}

streaming_history %.%
  {
    mutate(date = lubridate::floor_date(end_time, unit = "month"))
    count(date, artist_name, track_name)
    right_join(top_songs, by = c("track_name", "artist_name"))
  } %>%
  ggplot(aes(x = date, y = n, color = track_name)) +
  geom_line() +
  geom_point() +
  scale_color_excel_new(
    "Atlas",
    labels = function(x) {
      str_wrap(x, width = 25)
    },
    guide = guide_legend(nrow = 2, title = NULL)
  ) +
  scale_x_datetime(date_breaks = "2 months", date_labels = "%b %Y") +
  labs(
    title = "The frequency of my top songs",
    subtitle = "The number of times each song was played per month."
  )
```

```{r, fig.height=10}
pal <- c(excel_new_pal("Atlas")(6), "other" = pal_538[["Dark Gray"]])

streaming_history %.%
  {
    mutate(
      artist_name = fct_other(artist_name, keep = top_artists, other_level = "other"),
      date = lubridate::floor_date(end_time, "week")
    )
    count(artist_name, date, name = "n")
  } %>%
  ggplot(aes(x = date, y = n, color = artist_name)) +
  facet_wrap(artist_name ~ ., scales = "free_y", ncol = 1) +
  geom_col(
    aes(color = artist_name, fill = artist_name),
    position = "dodge",
    alpha = 0.5
  ) +
  geom_smooth(
    method = "loess",
    formula = "y~x",
    alpha = 0.7,
    se = FALSE,
    span = 0.5
  ) +
  scale_color_manual(values = pal) +
  scale_fill_manual(values = pal) +
  theme(
    strip.text = element_text(face = "bold"),
    legend.position = "none"
  ) +
  labs(
    title = "Trends in listening to my favorite artists"
  )
```

```{r}
pal <- c(excel_new_pal("Office Theme")(6), "other" = pal_538[["Medium Gray"]])

streaming_history %.%
  {
    filter(artist_name == "Quinn XCII")
    mutate(
      track_name = fct_lump_n(
        track_name,
        n = length(pal) - 1,
        other_level = "other"
      ),
      date = lubridate::floor_date(end_time, "month"),
    )
    count(date, track_name)
  } %>%
  ggplot(
    aes(x = date, y = n, color = track_name, fill = track_name)
  ) +
  geom_col(position = "stack") +
  scale_color_manual(
    values = pal
  ) +
  scale_fill_manual(
    values = pal
  ) +
  scale_x_datetime(
    date_breaks = "2 months",
    date_labels = "%b %Y",
    expand = expansion(add = c(0, 0))
  ) +
  theme(
    legend.position = "top",
    legend.key.size = unit(0.5, "cm"),
  ) +
  labs(
    y = "times listened",
    color = NULL,
    fill = NULL,
    title = "Trend of favorite songs by Quinn XCII"
  )
```

```{r}
sec_axis_coef <- 2
artist_color <- pal_538[["Red"]]
track_color <- pal_538[["Blue"]]

streaming_history %.%
  {
    mutate(mo_year = lubridate::floor_date(end_time, "month"))
    group_by(mo_year)
    summarise(
      num_artists = n_distinct(artist_name),
      num_tracks = n_distinct(track_name)
    )
    ungroup()
    mutate(num_tracks = num_tracks / sec_axis_coef)
  } %>%
  ggplot(aes(x = mo_year)) +
  geom_line(aes(y = num_artists), color = artist_color, alpha = 0.7) +
  geom_line(aes(y = num_tracks), color = track_color, alpha = 0.7) +
  geom_point(aes(y = num_artists), color = artist_color) +
  geom_point(aes(y = num_tracks), color = track_color) +
  scale_y_continuous(
    name = "num. artists",
    sec.axis = sec_axis(~ . * sec_axis_coef, name = "num. tracks")
  ) +
  scale_x_datetime(
    date_breaks = "2 months",
    date_labels = "%b %Y"
  ) +
  theme(
    axis.title.y = element_text(color = colorspace::darken(artist_color)),
    axis.title.y.right = element_text(color = colorspace::darken(track_color))
  ) +
  labs(
    title = "Variability in artists and songs",
    subtitle = "The number of different artists (red) and songs (blue) listened to each month."
  )
```

interesting ideas:
